# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\contacts_v1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_contactswindow(object):
    def setupUi(self, contactswindow):
        contactswindow.setObjectName("contactswindow")
        contactswindow.resize(268, 128)
        self.verticalLayout = QtWidgets.QVBoxLayout(contactswindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=contactswindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_ok = QtWidgets.QPushButton(parent=contactswindow)
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)

        self.retranslateUi(contactswindow)
        QtCore.QMetaObject.connectSlotsByName(contactswindow)

    def retranslateUi(self, contactswindow):
        _translate = QtCore.QCoreApplication.translate
        contactswindow.setWindowTitle(_translate("contactswindow", "Контакты"))
        self.label.setText(_translate("contactswindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Создателя зовут: Никита!</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Связаться можно через:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    * <a href=\"https://t.me/TheNikGreat\"><span style=\" text-decoration: underline; color:#0000ff;\">Личные сообщения</span></a> Telegram</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    * <a href=\"https://t.me/+m-aH1FUluAY4ODli\"><span style=\" text-decoration: underline; color:#0000ff;\">Канал</span></a> в Telegram</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    * <a href=\"https://github.com/ThNikGhost\"><span style=\" text-decoration: underline; color:#0000ff;\">Github</span></a></p></body></html>"))
        self.btn_ok.setText(_translate("contactswindow", "ОК"))
