# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\dialog_v1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_new_category(object):
    def setupUi(self, Dialog_new_category):
        Dialog_new_category.setObjectName("Dialog_new_category")
        Dialog_new_category.resize(266, 125)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_new_category)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog_new_category)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(11)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_newCateg = QtWidgets.QLineEdit(parent=Dialog_new_category)
        self.lineEdit_newCateg.setObjectName("lineEdit_newCateg")
        self.verticalLayout.addWidget(self.lineEdit_newCateg)
        self.Dialog_yesNo = QtWidgets.QDialogButtonBox(parent=Dialog_new_category)
        self.Dialog_yesNo.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Dialog_yesNo.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Dialog_yesNo.setObjectName("Dialog_yesNo")
        self.verticalLayout.addWidget(self.Dialog_yesNo)

        self.retranslateUi(Dialog_new_category)
        self.Dialog_yesNo.accepted.connect(Dialog_new_category.accept) # type: ignore
        self.Dialog_yesNo.rejected.connect(Dialog_new_category.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_new_category)

    def retranslateUi(self, Dialog_new_category):
        _translate = QtCore.QCoreApplication.translate
        Dialog_new_category.setWindowTitle(_translate("Dialog_new_category", "Внимание!"))
        self.label.setText(_translate("Dialog_new_category", " Напишите название новой категории:"))
