# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\form_addrec.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form_addrec(object):
    def setupUi(self, form_addrec):
        form_addrec.setObjectName("form_addrec")
        form_addrec.resize(217, 108)
        self.gridLayout = QtWidgets.QGridLayout(form_addrec)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox_ = QtWidgets.QDialogButtonBox(parent=form_addrec)
        self.buttonBox_.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox_.setObjectName("buttonBox_")
        self.gridLayout.addWidget(self.buttonBox_, 4, 0, 1, 2)
        self.lineEdit_addrec = QtWidgets.QLineEdit(parent=form_addrec)
        self.lineEdit_addrec.setObjectName("lineEdit_addrec")
        self.gridLayout.addWidget(self.lineEdit_addrec, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=form_addrec)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=form_addrec)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_123 = QtWidgets.QComboBox(parent=form_addrec)
        self.comboBox_123.setObjectName("comboBox_123")
        self.comboBox_123.addItem("Смотрю")
        self.comboBox_123.addItem("Любимые")
        self.comboBox_123.addItem("Просмотренные")
        self.comboBox_123.addItem("Брошенные")
        self.gridLayout.addWidget(self.comboBox_123, 1, 1, 1, 1)

        self.retranslateUi(form_addrec)
        QtCore.QMetaObject.connectSlotsByName(form_addrec)

    def retranslateUi(self, form_addrec):
        _translate = QtCore.QCoreApplication.translate
        form_addrec.setWindowTitle(_translate("form_addrec", "Добавить запись."))
        self.label.setText(_translate("form_addrec", "Название:"))
        self.label_2.setText(_translate("form_addrec", "Выберите:"))