# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\infowindow_v1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_infoWindow(object):
    def setupUi(self, infoWindow):
        infoWindow.setObjectName("infoWindow")
        infoWindow.resize(431, 179)
        self.verticalLayout = QtWidgets.QVBoxLayout(infoWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=infoWindow)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.btn_ok = QtWidgets.QPushButton(parent=infoWindow)
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)

        self.retranslateUi(infoWindow)
        QtCore.QMetaObject.connectSlotsByName(infoWindow)

    def retranslateUi(self, infoWindow):
        _translate = QtCore.QCoreApplication.translate
        infoWindow.setWindowTitle(_translate("infoWindow", "Очень важная информация!"))
        self.label.setText(_translate("infoWindow", "<html><head/><body><p>Это программа созданная для личного пользования, <br>но для большего опыта создаются все пришедшие в голову функции.</p><p>Если Вам попала в руки эта программа, то напишите мне!</p><p>Информацию о том, как можно связаться с создателем,<br> найдёте в соответсвующем меню </p><p><span style=\" font-family:\'Fira Sans\',\'Arial\'; font-size:13px; color:#656565; background-color:#f1f1f1;\">ヽ(・∀・)ﾉ</span></p></body></html>"))
        self.btn_ok.setText(_translate("infoWindow", "ОК"))
