# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\main_v1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindowChoose(object):
    def setupUi(self, mainWindowChoose):
        mainWindowChoose.setObjectName("mainWindowChoose")
        mainWindowChoose.resize(226, 278)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindowChoose.sizePolicy().hasHeightForWidth())
        mainWindowChoose.setSizePolicy(sizePolicy)
        mainWindowChoose.setBaseSize(QtCore.QSize(350, 500))
        self.centralwidget = QtWidgets.QWidget(parent=mainWindowChoose)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout.setContentsMargins(20, 0, 20, -1)
        self.verticalLayout.setSpacing(18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.chooseCategory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chooseCategory.setObjectName("chooseCategory")
        self.verticalLayout_2.addWidget(self.chooseCategory)
        self.btn_DeleteCategory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_DeleteCategory.setObjectName("btn_DeleteCategory")
        self.verticalLayout_2.addWidget(self.btn_DeleteCategory)
        mainWindowChoose.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindowChoose)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 226, 22))
        self.menubar.setObjectName("menubar")
        self.menuinfo = QtWidgets.QMenu(parent=self.menubar)
        self.menuinfo.setObjectName("menuinfo")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindowChoose.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(parent=mainWindowChoose)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(parent=mainWindowChoose)
        self.actionAbout.setObjectName("actionAbout")
        self.actionContacts = QtGui.QAction(parent=mainWindowChoose)
        self.actionContacts.setObjectName("actionContacts")
        self.menuinfo.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionContacts)
        self.menubar.addAction(self.menuinfo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindowChoose)
        QtCore.QMetaObject.connectSlotsByName(mainWindowChoose)

    def retranslateUi(self, mainWindowChoose):
        _translate = QtCore.QCoreApplication.translate
        mainWindowChoose.setWindowTitle(_translate("mainWindowChoose", "Меню выбора категории."))
        self.chooseCategory.setText(_translate("mainWindowChoose", "Добавить новую категорию:"))
        self.btn_DeleteCategory.setText(_translate("mainWindowChoose", "Удалить категорию"))
        self.menuinfo.setTitle(_translate("mainWindowChoose", "File"))
        self.menuHelp.setTitle(_translate("mainWindowChoose", "Help"))
        self.actionQuit.setText(_translate("mainWindowChoose", "Quit"))
        self.actionAbout.setText(_translate("mainWindowChoose", "About"))
        self.actionContacts.setText(_translate("mainWindowChoose", "Contacts"))

    