# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\table_v1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tableWindow(object):
    def setupUi(self, tableWindow):
        tableWindow.setObjectName("tableWindow")
        tableWindow.resize(561, 307)
        self.gridLayout = QtWidgets.QGridLayout(tableWindow)
        self.gridLayout.setObjectName("gridLayout")
        
        self.btn_move = QtWidgets.QPushButton(parent=tableWindow)
        self.btn_move.setObjectName("btn_move")
        self.gridLayout.addWidget(self.btn_move, 2, 4, 1, 1)
        self.btn_addRecord = QtWidgets.QPushButton(parent=tableWindow)
        self.btn_addRecord.setObjectName("btn_addRecord")
        self.gridLayout.addWidget(self.btn_addRecord, 2, 1, 1, 1)
        self.btn_removedRecord = QtWidgets.QPushButton(parent=tableWindow)
        self.btn_removedRecord.setObjectName("btn_removedRecord")
        self.gridLayout.addWidget(self.btn_removedRecord, 2, 2, 1, 1)
        self.btn_returnMenu = QtWidgets.QPushButton(parent=tableWindow)
        self.btn_returnMenu.setObjectName("btn_returnMenu")
        self.gridLayout.addWidget(self.btn_returnMenu, 2, 0, 1, 1)
        self.btn_settings = QtWidgets.QPushButton(parent=tableWindow)
        self.btn_settings.setObjectName("btn_settings")
        self.gridLayout.addWidget(self.btn_settings, 2, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 5)
        self.retranslateUi(tableWindow)
        #
        QtCore.QMetaObject.connectSlotsByName(tableWindow)

    def retranslateUi(self, tableWindow):
        _translate = QtCore.QCoreApplication.translate
        tableWindow.setWindowTitle(_translate("tableWindow", "Form"))
        self.btn_move.setText(_translate("tableWindow", "Переместить..."))
        self.btn_addRecord.setText(_translate("tableWindow", "Добавить запись"))
        self.btn_removedRecord.setText(_translate("tableWindow", "Удалить запись"))
        self.btn_returnMenu.setText(_translate("tableWindow", "Вернуться"))
        self.btn_settings.setText(_translate("tableWindow", "Настройки"))
