# Form implementation generated from reading ui file 'c:\MY FILES\ник\vscode\VPCLD_GUI\VPCLD-GUI\designer\window_move.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form_move(object):
    def setupUi(self, form_move):
        form_move.setObjectName("form_move")
        form_move.resize(238, 103)
        self.gridLayout = QtWidgets.QGridLayout(form_move)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=form_move)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_move = QtWidgets.QComboBox(parent=form_move)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_move.setFont(font)
        self.comboBox_move.setObjectName("comboBox_move")
        self.comboBox_move.addItem("Смотрю")
        self.comboBox_move.addItem("Любимые")
        self.comboBox_move.addItem("Просмотренные")
        self.comboBox_move.addItem("Брошенные")
        self.gridLayout.addWidget(self.comboBox_move, 1, 1, 1, 1)
        self.label_record = QtWidgets.QLabel(parent=form_move)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_record.setFont(font)
        self.label_record.setText("")
        self.label_record.setWordWrap(True)
        self.label_record.setObjectName("label_record")
        self.gridLayout.addWidget(self.label_record, 0, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=form_move)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(form_move)
        QtCore.QMetaObject.connectSlotsByName(form_move)

    def retranslateUi(self, form_move):
        _translate = QtCore.QCoreApplication.translate
        form_move.setWindowTitle(_translate("form_move", "Выберите куда переместить"))
        self.label_2.setText(_translate("form_move", "переместить в .."))
